creator:
  mode: create   # optimize or create

  # file directories
  data_ingest_dir: ./data/data_to_ingest_1
  simulator_prompts_filepath: ./config/simulator_prompts.yaml
  chatbot_prompts_filepath: ./config/query_handler_prompts.yaml

  # LLM models for different agents
  input_doc_agent:
    provider: azure_async
    model_name: gpt-4.1-mini
    temperature: 0.2
  prompt_creator:
    provider: azure_async
    model_name: gpt-4.1-mini
    temperature: 0.2
  reasoning_creator:
    provider: azure_async
    model_name: gpt-4.1-mini
    temperature: 0.2
  prompt_validator:
    provider: azure_async
    model_name: gpt-4.1-mini
    temperature: 0.2
  prompt_optimizer:
    provider: azure_async
    model_name: gpt-4.1-mini
    temperature: 0.2


defaults:
  - _self_
  - input_doc_agent_prompts
  - prompt_creator_prompts
  - reasoning_agent_template
  - reasoning_creator_prompts
  - prompt_validator_prompts 
  - prompt_optimizer_prompts 
