llm:
  provider: OpenAI
  model: gpt-4o-mini
  embedding_model: text-embedding-3-small

gdrive:
  credentials_path: ./credentials/fogg-447610-5249b63197be.json

# gdrive_doc:
#   - file_id: 11pL99aBsV_SmLOv67LdMmDkE9SiExWrrB9wzP2cPfUE
#     file_type: sheets
#   - file_id: 1Z5ovVwlVu9ZUgeAUorTPkzBIcjm72YeR2m3SY3ktiKU
#     file_type: docs

local_doc:
  paths:
    - path: ./data/data_to_ingest/syn_data.xlsx
    - path: ./data/data_to_ingest/rag_qna.pdf
  csv_dir: ./data/csv
  rows_threshold: 2  # Default is 50, Set low for testing RAG

chunker:
  token_threshold: 10  # switch between RAG and long-context, set low for testing RAG
  chunk_size: 300   # character count
  chunk_overlap: 100  # character overlap

embedder:
  similarity_metric: cosine  # cosine(default), L2, ip(Inner Product)
  persist_dir: ./data/embeddings
  collection: syn_data
  vector_store: chromadb

defaults:
  - _self_
  - extract_metadata