mongodb:
  db_name: syn_db  # Database name in MongoDB
  chat_history_collection: chat_history
  session_collection: sessions
  timeout_hours: 0.1


session_chat_limit: 100
session_customer_chat_limit: 100
ragas_base_dir: ./evaluations/ragas_reports
save_results: True
session_ids:
  - test_session
ground_truth:
