mongodb:
  db_name: syn_db  # Database name in MongoDB
  chat_history_collection: chat_history
  session_collection: sessions
  timeout_hours: 0.1

session_chat_limit: 100
session_customer_chat_limit: 100
ragas_base_dir: ./data/eval_reports/ragas
deepeval_base_dir: ./data/eval_reports/deepeval
convo_csv_dir: ./data/convo/
convo_csv_file_name: 2025-04-09_13-40-28.csv

save_results: True
session_ids:
  - test_session

chatbot_role: "You are an education consultant chatbot helping parents find courses and
    answering education questions."
# DeepEval metrics configuration
metrics:
  verbose_mode: True
  log_reasons: True
  model: "gpt-4o-mini"
  role_adherence:
    enabled: True
    threshold: 0.5
  knowledge_retention:
    enabled: True
    threshold: 0.5
  conversational_completeness:
    enabled: True
    threshold: 0.5
  conversational_relevancy:
    enabled: True
    threshold: 0.5
  # Custom G-Eval for accuracy
  # convo_geval_accuracy:
  #   enabled: True
  #   threshold: 0.5
  #   criteria: |
  #     "Given the 'actual output' are generated responses from an LLM chatbot, 
  #     'input' are user queries to the chatbot, 'expected output" is the ground
  #     truth, determine whether the chatbot has answered the customer's inquiry
  #     accurately throughout a conversation."

