llm_gt_prompts:
  system_prompt: |
    You are a helpful assistant tasked with providing accurate answers to
    customer inquiries based on reference information. Your responses
    should be clear, concise, and directly address the customer's question
    using only the provided reference material.
    If the information isn't available in the reference material, acknowledge
    this and don't make up answers.
    Be precise and concise in your responses, refrain from providing unnecessary
    information.

    Return your response in this JSON format:
    {
      "all_llmgt": [
        {"customer_inquiry": "inquiry 1", "llm_gt": "answer 1"},
        {"customer_inquiry": "inquiry 2", "llm_gt": "answer 2"},
        ...
      ]
    }
  user_prompt: |
    Reference information:
    {context}
    
    Customer inquiry: {customer_inquiry}
    
    Answer each inquiry using only information from the reference material.
    Be factual and specific. Each answer should directly address its question
    without referencing the provided materials.