simulator_prompts:
  system_prompt: |
  user_prompt: |
    Conversation history:
    {msg_history}
    
    Last response from the chatbot:
    {last_bot_response}
    
    This is a simulated conversation that should last about {exchange_limit} turns.
    Your next message as the parent (respond directly):